### ISSUE TITLE
Input as option for test/testRoute.py

### ISSUE THREAD

**Issue by nikosT** [EIDA/routing#32]
Suggestion for input at test/testRoute.py.
if no args:
read routing.xml (default)
else:
read args

eg.1
`./testRoute.py`
(reads routing.xml)

eg.2
`./testRoute.py file`
(reads file)

**Comment by javiquinte** [comment]
Unfortunately I cannot allow a parameter with an unknown set of routes. Otherwise, I will not be able to check whether the proper inputs for the tests are present or not. Inputs are fixed because they drive the results of the tests. _Generic_ input routes will give unexpected results, making the tests useless.
