### ISSUE TITLE
doc: specification / input parameter service

### ISSUE THREAD

**Issue by petrrr** [EIDA/routing#64]
The specifications states the following regarding the service parameter:

Parameter | Support | Format | Description | Default
-- | -- | -- | -- | --
|service | Required | char | Specify which service will be queried (dataselect, station, etc). | dataselect

In particular the description ("dataselect, station, etc.") is not adequate for a specification which needs to be self-containted and explicit. 

Please list possible values, and also which are required vs. which are optional.

**Comment by javiquinte** [comment]
If you mean to add a note mentioning the ones generally used in EIDA, I could do it. No problem.
If you mean something else, like checking something in the code, or limiting the values in the specification is much more complicated.
The Routing Service is open to allow in the future the inclusion of different services (standard and non-standard). From the point of view of the specification (and the code) there are no limitations to the services you can include. Mainly because the code will not check that. That would be a strong limitation to its functionality.
When we had to include the WFCatalog, we just agreed on the name in 30 seconds and it worked. We didn't need to upgrade the software.
RESIF, for instance, plans to include other services that we don't support as EIDA. We need to remember that this will be exported downstream to the FDSN Data Centre Registry.

**Comment by petrrr** [comment]
Well I stepped into this while trying to fix the application.wadl. 

I still think a specification needs to be clear on what is to be expected from a service, or what a user can expect from a service. It is **not** (necessary) about the software itself. 

So okay, when you decided to include the wfcatalog as a service you basically changed the specification of the service, at least implicitly,  and not the software itself. But such changes need to happen more explicitly. Just imagine you would want to implement the software based on the specs. You need to know which features are required, which are optional and also which kind of extensions are admissible.

So maybe in this specific case, choose the set of services which are expected to be supported (required), that only specified names are reserved (required and optional), state that other services may be included as an extension, but that unspecified names are not reserved or protected.

**Comment by javiquinte** [comment]
#65 accepted, merged and new stable release available ( v1.2.1 )
https://github.com/EIDA/routing/releases/tag/v1.2.1
