### ISSUE TITLE
Issue with UIB harvesting?

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/routing#74]
When trying to get UIB routing, following error occurs:
```
WARNING:addRemote:The URL does not seem to be a valid Routing Service
WARNING:addRemote:http://eida.geo.uib.no/eidaws/routing.xml/localconfig - Reason: Not Found
```

**Comment by javiquinte** [comment]
Hi @jbienkowski 
That is only a warning and I guess that this happens because the first attempt is to consider that it points to a Routing Service. If this does not work (like in this case), you should see below that the code tries to download an XML file from the URL.

So far, this is no error at all. I'll close it, but please open it again if you see that no routes can be downloaded after the warning.

**Comment by damb** [comment]
@javiquinte, I've got a question which somehow is related and somehow might be OT: 

What's the point of the distinction between fetching the `localconfig` from an `eidaws-routing` instance vs fetching the `localconfig` without appending the `localconfig` suffix to the URL path in https://github.com/EIDA/routing/blob/master/routeutils/utils.py#L1143-L1256? Wouldn't it be good enough to read the `localconfig` either from any URL or rather from a file URI, respectively? Do I miss something here?

Thanks.

**Comment by jbienkowski** [comment]
Sorry, @javiquinte. I've had some issues with it yesterday, on a bank holiday and created this in an incredible rush.
In the end it was related to Docker service, as usual. ;-)

**Comment by javiquinte** [comment]
> What's the point of the distinction between fetching the `localconfig` from an `eidaws-routing` instance vs fetching the `localconfig` without appending the `localconfig` suffix to the URL path in https://github.com/EIDA/routing/blob/master/routeutils/utils.py#L1143-L1256? Wouldn't it be good enough to download/read the `localconfig` either from any URL or rather from a file URI, respectively? Do I miss something here?

The idea was to input just the URL for the Routing Service because it looked nicer for two reasons.
1. As an operator, you probably don't want to know the details of the different methods of the Routing Service. Just deploy it and add the URL of the service. The code will choose the proper method.
1. The harvesting process could turn more complex in the future and involve different methods, and not only localconfig

In any case, it is always subjective if the approach is the best or not. It was just a decision.

**Comment by damb** [comment]
> In any case, it is always subjective if the approach is the best or not. It was just a decision.

Got it. So the idea was to relate a `localconfig` to a `eidaws-routing` service deployment ...
